### ISSUE TITLE
What is required in order to start using IoRing

### ISSUE THREAD

**Issue by wbuck** [yardenshafir/IoRing_Demos#4]
So I've been trying to use `IoRing` in a little test application that I've written and I've run into an issue that I'm hoping you can help me with as you appear to be the go-to resource on the Windows `IoRing` at the moment (I'm finding the MS documentation a little lacking in this regard).

Currently all I'm doing is calling [QueryIoRingCapabilities](https://docs.microsoft.com/en-us/windows/win32/api/ioringapi/nf-ioringapi-queryioringcapabilities) and then `switch`ing on the `MaxVersion`. 

When I attempt to run the application I get an error message about missing the `api-ms-win-core-ioring-l1-1-0.dll`.

I'm clearly missing something but I'm unsure as to what I need in order to write an application using the `IoRing`.
My dev machine is a Windows 10 Version 21H2; which I thought meant that I could use the `IoRing` for reading (no write or flush support).

Is there a specific `SDK` I should install? 
Do I need to be a Windows Insider in order to test out this API?

I know this issue doesn't directly pertain to this repo but I was still hoping you might have some additional insight in to what I need installed on my dev machine in order to test out the `IoRing`?

**Comment by yardenshafir** [comment]
To use I/O rings you'll need to include the header file ioringapi.h, that exists starting SDK 22000 (the Windows 11 SDK). If you don't have that installed, start there.
If that doesn't fix the issues, try linking your application against OneCoreUap.lib.
The `IoRingPerf` project in this repository should work on Windows 21h2 as long as you have the correct SDK (22000+), so if nothing works you can start there :)
Good luck and hope this helps!

**Comment by wbuck** [comment]
Thank-you for the reply (especially considering this wasn't about your repo).
